  // WHILE
//    while (condition) {
    
//  }       

// let index=0;
// while (index<=10) {
//     console.log(`value of index ${index}`);
//     index++
    
// }

// let myarray =["flash", "batman","superman"]

// let arr=0
// while (arr<Array.length) {

//     console.log(`value of index ${myarray}`);
//     arr++
    
// }

let score =1 
do {
    console.log(`score is ${score}`);
    score++
} while (score <=10);